//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST_API_ASP.Net.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public partial class Post
    {
        //public Post()
        //{
        //    this.Comment = new HashSet<Comment>();
        //}

        public int PostId { get; set; }
        public string Post1 { get; set; }
        public Nullable<int> UserId { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [XmlIgnore,JsonIgnore]
        //public virtual Comment Comment { get; set; }

        public  ICollection<Comment> Comment { get; set; }
        //public  Comment Comment { get; set; }
    }
}
